# Dependabot will run on day 27 of each month at 01:52 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      day: 25
      timezone: "Europe/Berlin"
      cronjob: "52 1 27 * *"
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
    versioning-strategy: "increase"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "cron"
      day: 25
      timezone: "Europe/Berlin"
      cronjob: "52 1 27 * *"
    open-pull-requests-limit: 15
    assignees:
      - "patricknitsch"
